// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ChannelsGet implements GET /channels operation.
	//
	// Retrieves all channels based on provided IDs.
	//
	// GET /channels
	ChannelsGet(ctx context.Context, params ChannelsGetParams) (ChannelsGetRes, error)
	// ChannelsPost implements POST /channels operation.
	//
	// Creates channels by fetching from Youtube using provided Channel IDs.
	//
	// POST /channels
	ChannelsPost(ctx context.Context, req *ChannelsPostReq) (ChannelsPostRes, error)
	// ChannelsPut implements PUT /channels operation.
	//
	// Updates channels by fetching from Youtube using provided Channel IDs.
	//
	// PUT /channels
	ChannelsPut(ctx context.Context, req *ChannelsPutReq) (ChannelsPutRes, error)
	// ClipsGet implements GET /clips operation.
	//
	// Retrieve all clips.
	//
	// GET /clips
	ClipsGet(ctx context.Context, params ClipsGetParams) (ClipsGetRes, error)
	// ClipsPut implements PUT /clips operation.
	//
	// Update clips based on provided cronType.
	//
	// PUT /clips
	ClipsPut(ctx context.Context, req *ClipsPutReq) (ClipsPutRes, error)
	// SongsGet implements GET /songs operation.
	//
	// Retrieve all songs.
	//
	// GET /songs
	SongsGet(ctx context.Context) (SongsGetRes, error)
	// SongsPost implements POST /songs operation.
	//
	// Updates songs by fetching from Youtube using provided Video IDs.
	//
	// POST /songs
	SongsPost(ctx context.Context, req *SongsPostReq) (SongsPostRes, error)
	// SongsPut implements PUT /songs operation.
	//
	// Update songs based on provided cronType.
	//
	// PUT /songs
	SongsPut(ctx context.Context, req *SongsPutReq) (SongsPutRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
