// Code generated by ogen, DO NOT EDIT.
package api

type ChannelsGetRes interface {
	channelsGetRes()
}

type ChannelsPostRes interface {
	channelsPostRes()
}

type ChannelsPutRes interface {
	channelsPutRes()
}

type ClipsGetRes interface {
	clipsGetRes()
}

type ClipsPutRes interface {
	clipsPutRes()
}

type SongsGetRes interface {
	songsGetRes()
}

type SongsPostRes interface {
	songsPostRes()
}

type SongsPutRes interface {
	songsPutRes()
}
