openapi: 3.0.1
info:
  title: VSPO Common API
  description: This is the API documentation for VSPO Common services.
  contact: {}
  version: "1.0"
servers:
- url: /api
paths:
  /creators:
    get:
      tags:
        - Creators
      summary: Get Creators
      description: Retrieves all creators based on provided IDs.
      parameters:
      - name: creator_ids
        in: query
        description: A list of IDs that identify the creators you want to get. To get more than one creator, include this parameter for each creator you want to get. The creator_id and creator_id parameters are mutually exclusive.
        schema:
          type: string
        example: creator_id1,creator_id2,creator_id3
      - name: creator_type
        in: query
        description: A filter used to filter the list of creators by the creator's type.
        schema:
          type: string
          enum: [vspo]
        example: vspo
      - name: page
        in: query
        description: Pagination object. Specify this parameter only if you don't specify the creator_ids query parameter.
        schema:
          type: integer
      - name: limit
        in: query
        description: The maximum number of items to return per page(The default is 20.) Specify this parameter only if you don't specify the creator_ids query parameter.
        schema:
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/CreatorsResponse'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
  /videos:
    get:
      tags:
        - Videos
      summary: Get all videos for a specific creator
      description: Retrieve all videos related to a specific creator
      parameters:
      - name: video_ids
        in: query
        description: A list of IDs that identify the videos you want to get. To get more than one video, include this parameter for each video you want to get. The video_id and creator_id parameters are mutually exclusive.
        schema:
          type: string
        example: video_id1,video_id2,video_id3
      - name: creator_id
        in: query
        description: The ID of the creator whose list of videos you want to get. The video_id and creator_id parameters are mutually exclusive.
        schema:
          type: string
        example: creator_id
      - name: language
        in: query
        description: The ISO 639-1 two-letter code for Japanese (i.e., ja)
        schema:
          type: string
        example: ja
      - name: video_type
        in: query
        description: A filter used to filter the list of videos by the video's type.(The default is "vspo_broadcast".)
        schema:
          type: array
          items:
            type: string
          enum: [vspo_broadcast, clip, freechat]
        example: broadcast
      - name: broadcast_status
        in: query
        description: A filter used to filter the list of videos by the video's vspo_broadcast type.
        schema:
          type: array
          items:
            type: string
          enum: [live, upcoming, archive]
        example: live
      - name: period
        in: query
        description: A filter used to filter the list of videos by when they were published.
        schema:
          type: string
          enum: [day, month, week]
        example: day
      - name: sort
        in: query
        description: The order to sort the returned videos.(The default is "time".)
        schema:
          type: string
          enum: [time, trending, views]
        example: time
      - name: platform_type
        in: query
        description: A filter used to filter the list of videos by the video's platform type.
        schema:
          type: array
          items:
            type: string
          enum: [youtube, twitch, twitcasting, niconico]
        example: youtube
      - name: page
        in: query
        description: Pagination object. Specify this parameter only if you don't specify the creator_id or video_ids query parameter.
        schema:
          type: integer
      - name: limit
        in: query
        description: The maximum number of items to return per page(The default is 20.) Specify this parameter only if you don't specify the creator_id or video_ids query parameter.
        schema:
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/VideosResponse'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
    put:
      tags:
        - Videos
      summary: Update videos for a specific creator
      description: Update videos related to a specific creator based on provided cronType
      requestBody:
        description: Type of the cron
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                video_ids:
                  type: array
                  items:
                    type: string
                  description: Array of YouTube Video IDs.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideosResponse'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
    post:
      tags:
        - Videos
      summary: Create videos for a specific creator
      description: Update videos related to a specific creator based on provided cronType
      requestBody:
        description: Type of the cron
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                video_ids:
                  type: array
                  items:
                    type: string
                  description: Array of YouTube Video IDs.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideosResponse'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas:
    CreatorsResponse:
      type: object
      properties:
        creators:
          type: array
          items:
            $ref: '#/components/schemas/CreatorResponse'
        pagination:
            $ref: '#/components/schemas/Pagination'
    CreatorResponse:
      type: object
      properties:
        creator_id:
          type: string
          example: UCiMG6VdScBabPhJ1ZtaVmbw
        creator_name:
          type: string
          example:
        channel_info:
          $ref: '#/components/schemas/ChannelResponse'
    ChannelResponse:
      type: object
      properties:
        youtube:
          $ref: '#/components/schemas/ChannelPlatformSnippet'
        twitch:
          $ref: '#/components/schemas/ChannelPlatformSnippet'
        twitCasting:
          $ref: '#/components/schemas/ChannelPlatformSnippet'
        niconico:
          $ref: '#/components/schemas/ChannelPlatformSnippet'
    ChannelPlatformSnippet:
      type: object
      properties:
        channel_id:
          type: string
        name:
          type: string
        description:
          type: string
        thumbnail_url:
          type: string
    VideosResponse:
      type: object
      properties:
        videos:
          type: array
          items:
            $ref: '#/components/schemas/VideoResponse'
        pagination:
            $ref: '#/components/schemas/Pagination'
    VideoResponse:
      type: object
      properties:
        video_id:
          type: string
          example: Qh6aSTTkmEs
        title:
          type: string
          example: 【ぶいすぽっ！】Blessing ~12人で歌ってみた~
        description:
          type: string
          example: ""
        published_at:
          type: string
          example: 2020-12-31T12:34:56+09:00
          format: date-time
        started_at:
          type: string
          example: 2020-12-31T12:34:56+09:00
          format: date-time
        ended_at:
          type: string
          example: 2020-12-31T12:34:56+09:00
          format: date-time
        tags:
          type: array
          items:
            type: string
        thumbnail_url:
          type: string
          example: https://i.ytimg.com/vi/Qh6aSTTkmEs/default.jpg
        platform:
          type: string
          example: youtube
          enum: [youtube, twitch, twitcasting, niconico, unknown]
        views:
          $ref: '#/components/schemas/ViewsResponse'
        creator_info:
          type: object
          properties:
            creator_id:
              type: string
              example: creator_id
            creator_name:
              type: string
              example: 花芽なずな
            thumbnail_url:
              type: string
              example: https://i.ytimg.com/vi/Qh6aSTTkmEs/default.jpg
    ViewsResponse:
      type: object
      properties:
        daily:
          type: string
          example: "1000"
        monthly:
          type: string
          example: "100000"
        total:
          type: string
          example: "1000000"
        weekly:
          type: string
          example: "10000"
    Pagination:
      type: object
      properties:
        currentPage:
          type: integer
          format: int64
        prevPage:
          type: integer
          format: int64
        nextPage:
          type: integer
          format: int64
        totalPage:
          type: integer
          format: int64
        totalCount:
          type: integer
          format: int64
        hasNext:
          type: boolean
security:
  - ApiKeyAuth: []

tags:
  - name: Creators
    description: Operations related to creators
  - name: Videos
    description: Operations related to videos

x-original-swagger-version: "2.0"
