openapi: 3.0.1
info:
  title: VSPO Common Cron
  description: This is the Cron documentation for VSPO Common services.
  contact: {}
  version: "1.0"
servers:
- url: /api/cron
paths:
  /channels:
    post:
      tags:
        - Channels
      summary: Upsert Channel(Youtube/Twitch/Twitcasting)
      description: Creates channels by fetching from Youtube using provided Channel IDs.
      requestBody:
        description: Array of Channel IDs
        content:
          application/json:
            schema:
              type: object
              properties:
                platform_type:
                  type: string
                  enum: [all, youtube, twitch, twitcasting, niconico]
                  description: Video's platform type.
                period:
                    type: string
                    enum: [all, day, month, week]
                    description: Period for performing updates.
        required: true
      responses:
        "200":
          description: Channels created successfully
          content:
            application/json:
              schema:
                type: string
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
        - ApiKeyAuth: []
        - YoutubeApiKey: []
        - TwitchApiKey: []
  /videos:
    post:
      tags:
        - Videos
      summary: Upsert videos
      description: Update videos related to a specific channel based on provided cronType
      requestBody:
        description: Type of the cron
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                platform_type:
                  type: string
                  enum: [all, youtube, twitch, twitcasting, niconico]
                  description: Video's platform type.
                period:
                    type: string
                    enum: [all, day, month, week]
                    description: Period for performing updates.
                video_type:
                    type: string
                    enum: [all, vspo_broadcast, clip, freechat]
      responses:
        "200":
          description: Videos updated successfully
          content:
            application/json:
              schema:
                type: string
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
        - ApiKeyAuth: []
        - YoutubeApiKey: []
        - TwitchApiKey: []

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
    YoutubeApiKey:
      type: apiKey
      in: header
      name: X-Youtube-API-Key
    TwitchApiKey:
      type: apiKey
      in: header
      name: X-Twitch-API-Key
security:
  - ApiKeyAuth: []
  - YoutubeApiKey: []
  - TwitchApiKey: []

tags:
  - name: Channels
    description: Operations related to channels
  - name: Videos
    description: Operations related to videos

