openapi: 3.0.1
info:
  title: VSPO Common API
  description: This is the API documentation for VSPO Common services.
  contact: {}
  version: "1.0"
servers:
- url: /api
paths:
  /creators:
    get:
      tags:
        - Creators
      summary: Get Creators
      description: Retrieves all creators based on provided IDs.
      parameters:
      - name: ids
        in: query
        description: Comma-separated list of creator IDs
        style: form
        explode: false
        schema:
          type: string
        example: abc,cde
      - name: page
        in: query
        description: page
        schema:
          type: integer
      - name: limit
        in: query
        description: page limit
        schema:
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/CreatorsResponse'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
  /videos:
    get:
      tags:
        - Videos
      summary: Get all videos for a specific creator
      description: Retrieve all videos related to a specific creator
      parameters:
      - name: creator_id
        in: query
        description: Unique identifier of the creator
        schema:
          type: string
      - name: ids
        in: query
        description: Comma-separated list of videos IDs
        schema:
          type: string
        example: abc,cde
      - name: start_date
        in: query
        description: Start Date
        schema:
          type: string
      - name: end_date
        in: query
        description: End Date
        schema:
          type: string
      - name: page
        in: query
        description: page
        schema:
          type: integer
      - name: limit
        in: query
        description: page limit
        schema:
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/VideosResponse'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
    put:
      tags:
        - Videos
      summary: Update videos for a specific creator
      description: Update videos related to a specific creator based on provided cronType
      requestBody:
        description: Type of the cron
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: string
                  description: Array of YouTube Video IDs.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideosResponse'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
    post:
      tags:
        - Videos
      summary: Create videos for a specific creator
      description: Update videos related to a specific creator based on provided cronType
      requestBody:
        description: Type of the cron
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: string
                  description: Array of YouTube Video IDs.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideosResponse'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas:
    VideosResponse:
      type: object
      properties:
        videos:
          type: array
          items:
            $ref: '#/components/schemas/VideoResponse'
        pagination:
            $ref: '#/components/schemas/Pagination'
    CreatorResponse:
      type: object
      properties:
        id:
          type: string
          example: UCiMG6VdScBabPhJ1ZtaVmbw
        name:
          type: string
          example: 花芽なずな
        channels:
          type: array
          items:
            $ref: '#/components/schemas/ChannelResponse'
    CreatorsResponse:
      type: object
      properties:
        creators:
          type: array
          items:
            $ref: '#/components/schemas/CreatorResponse'
        pagination:
            $ref: '#/components/schemas/Pagination'
    ChannelResponse:
      type: object
      properties:
        id:
          type: string
          example: UCiMG6VdScBabPhJ1ZtaVmbw
        snippet:
          $ref: '#/components/schemas/ChannelSnippetResponse'
        statistics:
          $ref: '#/components/schemas/ChannelStatisticsResponse'
        videos:
          type: array
          items:
            $ref: '#/components/schemas/VideoResponse'
    ChannelSnippetResponse:
      type: object
      properties:
        Youtube:
          $ref: '#/components/schemas/PlatformSnippet'
        Twitch:
          $ref: '#/components/schemas/PlatformSnippet'
        TwitCasting:
          $ref: '#/components/schemas/PlatformSnippet'
        Niconico:
          $ref: '#/components/schemas/PlatformSnippet'

    ChannelStatisticsResponse:
      type: object
      properties:
        Youtube:
          $ref: '#/components/schemas/PlatformStatistics'
        Twitch:
          $ref: '#/components/schemas/PlatformStatistics'
        TwitCasting:
          $ref: '#/components/schemas/PlatformStatistics'
        Niconico:
          $ref: '#/components/schemas/PlatformStatistics'
    ThumbnailResponse:
      type: object
      properties:
        height:
          type: integer
          example: 90
        url:
          type: string
          example: https://i.ytimg.com/vi/Qh6aSTTkmEs/default.jpg
        width:
          type: integer
          example: 120
    ThumbnailsResponse:
      type: object
      properties:
        default:
          $ref: '#/components/schemas/ThumbnailResponse'
        high:
          $ref: '#/components/schemas/ThumbnailResponse'
        maxres:
          $ref: '#/components/schemas/ThumbnailResponse'
        medium:
          $ref: '#/components/schemas/ThumbnailResponse'
        standard:
          $ref: '#/components/schemas/ThumbnailResponse'
    VideoResponse:
      type: object
      properties:
        channelId:
          type: string
          example: UCiMG6VdScBabPhJ1ZtaVmbw
        channelTitle:
          type: string
          example: 花芽なずな / Nazuna Kaga
        description:
          type: string
          example: ""
        id:
          type: string
          example: Qh6aSTTkmEs
        publishedAt:
          type: string
          example: 2020-12-31T12:34:56+09:00
          format: date-time
        startAt:
          type: string
          example: 2020-12-31T12:34:56+09:00
          format: date-time
        endAt:
          type: string
          example: 2020-12-31T12:34:56+09:00
          format: date-time
        tags:
          type: array
          items:
            type: string
        thumbnails:
          $ref: '#/components/schemas/ThumbnailsResponse'
        title:
          type: string
          example: 【ぶいすぽっ！】Blessing ~12人で歌ってみた~
        platform:
          type: string
          example: youtube
          enum: [youtube, twitch, twitcasting, niconico, unknown]
    ViewsResponse:
      type: object
      properties:
        daily:
          type: string
          example: "1000"
        monthly:
          type: string
          example: "100000"
        total:
          type: string
          example: "1000000"
        weekly:
          type: string
          example: "10000"
    Pagination:
      type: object
      properties:
        CurrentPage:
          type: integer
          format: int64
        PrevPage:
          type: integer
          format: int64
        NextPage:
          type: integer
          format: int64
        TotalPage:
          type: integer
          format: int64
        TotalCount:
          type: integer
          format: int64
        HasNext:
          type: boolean
    PlatformSnippet:
      type: object
      properties:
        Title:
          type: string
        Description:
          type: string
        CustomURL:
          type: string
        PublishedAt:
          type: string
          format: date-time
        Thumbnails:
          $ref: '#/components/schemas/ThumbnailsResponse'
    PlatformStatistics:
      type: object
      properties:
        ViewCount:
          type: string
        SubscriberCount:
          type: string
        HiddenSubscriberCount:
          type: boolean
        VideoCount:
          type: string
security:
  - ApiKeyAuth: []

tags:
  - name: Creators
    description: Operations related to creators
  - name: Videos
    description: Operations related to videos

x-original-swagger-version: "2.0"
