// Code generated by MockGen. DO NOT EDIT.
// Source: twitcasting.go
//
// Generated by this command:
//
//	mockgen -source=twitcasting.go -destination=mock/twitcasting.go -package=mock_twitcasting
//

// Package mock_twitcasting is a generated GoMock package.
package mock_twitcasting

import (
	context "context"
	reflect "reflect"

	model "github.com/sugar-cat7/vspo-portal/service/cron/domain/model"
	twitcasting "github.com/sugar-cat7/vspo-portal/service/cron/domain/twitcasting"
	gomock "go.uber.org/mock/gomock"
)

// MockTwitcastingClient is a mock of TwitcastingClient interface.
type MockTwitcastingClient struct {
	ctrl     *gomock.Controller
	recorder *MockTwitcastingClientMockRecorder
}

// MockTwitcastingClientMockRecorder is the mock recorder for MockTwitcastingClient.
type MockTwitcastingClientMockRecorder struct {
	mock *MockTwitcastingClient
}

// NewMockTwitcastingClient creates a new mock instance.
func NewMockTwitcastingClient(ctrl *gomock.Controller) *MockTwitcastingClient {
	mock := &MockTwitcastingClient{ctrl: ctrl}
	mock.recorder = &MockTwitcastingClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTwitcastingClient) EXPECT() *MockTwitcastingClientMockRecorder {
	return m.recorder
}

// GetVideos mocks base method.
func (m *MockTwitcastingClient) GetVideos(ctx context.Context, param twitcasting.TwitcastingVideosParam) (model.Videos, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideos", ctx, param)
	ret0, _ := ret[0].(model.Videos)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVideos indicates an expected call of GetVideos.
func (mr *MockTwitcastingClientMockRecorder) GetVideos(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideos", reflect.TypeOf((*MockTwitcastingClient)(nil).GetVideos), ctx, param)
}
