version: '3.8'

services:
  postgres:
    container_name: vspo-db
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vspo
    ports:
      - "5432:5432"
  go:
    container_name: vspo-cron-go
    build:
      context: .
      dockerfile: Dockerfile.cron
    volumes:
      - .:/project/
    working_dir: /project
    ports:
      - 8080:8080
  migration:
    container_name: vspo--db-migration
    build:
      context: .
      dockerfile: Dockerfile.migration
    volumes:
      - ./infra/database/internal/schema/migration:/migrations
      - .:/project
    environment:
      DBSTRING: "host=localhost user=user password=password dbname=vspo sslmode=disable"
