FROM golang:1.22.3-bullseye AS builder

ENV CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64


WORKDIR /project

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /main -ldflags="-s -w" ./cmd/index.go

FROM alpine:3.19.1

COPY --from=builder /main /main

EXPOSE 8080

CMD ["/main"]
