# Dockerfile-migration
FROM golang:1.22.1-bullseye as builder

# Install goose
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

# Use alpine for a lightweight final image
FROM alpine:latest
COPY --from=builder /go/bin/goose /usr/local/bin/goose

# Install runtime dependencies
RUN apk add --no-cache libc6-compat

# Set the working directory
WORKDIR /project

# Expose the volume for migrations
VOLUME /migrations
