# Dockerfile-go
FROM golang:1.22.3-bullseye

# Install air for live-reloading during development
RUN go install github.com/cosmtrek/air@latest

# Set the working directory
WORKDIR /project
COPY . /project

# Install dependencies
RUN go mod tidy

# Build the application
RUN go build -o ./tmp/main ./cmd/index.go

# Expose the port the app runs on
# EXPOSE 8080

# Command to run the application using air for live reloading
# CMD ["air"]
