// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db_sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Channel struct {
	ID                    string
	CreatorID             string
	PlatformName          string
	Title                 string
	Description           string
	PublishedAt           pgtype.Timestamptz
	TotalViewCount        int32
	SubscriberCount       int32
	HiddenSubscriberCount bool
	TotalVideoCount       int32
	ThumbnailUrl          string
	IsDeleted             bool
}

type Creator struct {
	ID         string
	Name       string
	MemberType string
}

type Video struct {
	ID              string
	ChannelID       string
	PlatformName    string
	Title           string
	Description     string
	VideoType       string
	PublishedAt     pgtype.Timestamptz
	StartAt         pgtype.Timestamptz
	EndAt           pgtype.Timestamptz
	BroadcastStatus string
	Tags            string
	ViewCount       int32
	ThumbnailUrl    string
	IsDeleted       bool
}
