services:
  vspo-db:
    container_name: vspo-db
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vspo
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "psql -U user -d vspo -c 'SELECT 1'"]
      interval: 2s
      timeout: 1s
      retries: 5
  vspo-db-migration:
    container_name: vspo-db-migration
    build:
      context: ..
      dockerfile: Dockerfile.migration
    volumes:
      - ../infra/database/schema/migration:/migration
    command: ["goose", "-dir", "/migration", "postgres", "host=vspo-db user=user dbname=vspo password=password sslmode=disable", "up"]
    depends_on:
      vspo-db:
        condition: service_healthy
  # vspo-cron-go:
  #   container_name: vspo-cron-go
  #   build:
  #     context: ..
  #     dockerfile: Dockerfile.local
  #   volumes:
  #     - ../:/project/
  #   working_dir: /project
  #   command: ["./tmp/main", "ping"]
  #   ports:
  #     - 8080:8080
  #   # env_file:
  #   #   - ../.env.local
