// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ChannelsGet implements GET /channels operation.
//
// Retrieves all channels based on provided IDs.
//
// GET /channels
func (UnimplementedHandler) ChannelsGet(ctx context.Context, params ChannelsGetParams) (r ChannelsGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ChannelsPost implements POST /channels operation.
//
// Creates channels by fetching from Youtube using provided Channel IDs.
//
// POST /channels
func (UnimplementedHandler) ChannelsPost(ctx context.Context, req *ChannelsPostReq) (r ChannelsPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ChannelsPut implements PUT /channels operation.
//
// Updates channels by fetching from Youtube using provided Channel IDs.
//
// PUT /channels
func (UnimplementedHandler) ChannelsPut(ctx context.Context, req *ChannelsPutReq) (r ChannelsPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ClipsGet implements GET /clips operation.
//
// Retrieve all clips.
//
// GET /clips
func (UnimplementedHandler) ClipsGet(ctx context.Context, params ClipsGetParams) (r ClipsGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ClipsPut implements PUT /clips operation.
//
// Update clips based on provided cronType.
//
// PUT /clips
func (UnimplementedHandler) ClipsPut(ctx context.Context, req *ClipsPutReq) (r ClipsPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SongsGet implements GET /songs operation.
//
// Retrieve all songs.
//
// GET /songs
func (UnimplementedHandler) SongsGet(ctx context.Context) (r SongsGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SongsPost implements POST /songs operation.
//
// Updates songs by fetching from Youtube using provided Video IDs.
//
// POST /songs
func (UnimplementedHandler) SongsPost(ctx context.Context, req *SongsPostReq) (r SongsPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SongsPut implements PUT /songs operation.
//
// Update songs based on provided cronType.
//
// PUT /songs
func (UnimplementedHandler) SongsPut(ctx context.Context, req *SongsPutReq) (r SongsPutRes, _ error) {
	return r, ht.ErrNotImplemented
}
