name = "prd-vspo-portal-gateway"
compatibility_date = "2024-10-22"
send_metrics = false
compatibility_flags = ["nodejs_compat", "nodejs_als"]
main = "cmd/server/gateway.ts"
# tail_consumers = [{ service = "prd-vspo-portal-gateway-tail" }]
logpush = true
kv_namespaces = [
  { binding = "APP_KV", id = "14bf3d407655490e9f377efbb4c3352b" }
]

[dev]
port = 3000

[[services]]
binding = "APP_WORKER"
service = "prd-vspo-portal-app"
entrypoint = "ApplicationService"

[vars]
SERVICE_NAME = "prd-vspo-portal-gateway"
ENVIRONMENT = "production"
LOG_TYPE = "json"
LOG_MINLEVEL = "1"
LOG_HIDE_POSITION = "true"

[observability]
enabled = true
