services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.54
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
  vspo-db:
    container_name: vspo-db
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vspo
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "psql -U user -d vspo -c 'SELECT 1'"]
      interval: 2s
      timeout: 1s
      retries: 5
  vspo-db-migration:
    container_name: vspo-db-migration
    build:
      context: ../service/common-job
      dockerfile: Dockerfile
      target: local-db-migration
    environment:
      DB_HOST: vspo-db
    volumes:
      - ../service/common-job/infra/database/schema/migration:/migration
    depends_on:
      vspo-db:
        condition: service_healthy
