services:
  vspo-db:
    container_name: vspo-db
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vspo
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "psql -U user -d vspo -c 'SELECT 1'"]
      interval: 2s
      timeout: 1s
      retries: 5
    networks:
      - vspo-network
  vspo-db-migration:
    container_name: vspo-db-migration
    build:
      context: ../service/common-job
      dockerfile: Dockerfile
      target: local-db-migration
    environment:
      DB_HOST: vspo-db
    volumes:
      - ../service/common-job/infra/database/schema/migration:/migration
    depends_on:
      vspo-db:
        condition: service_healthy
    networks:
      - vspo-network
  vspo-portal-cron:
    container_name: vspo-portal-cron
    build:
      context: ../service/common-job
      dockerfile: Dockerfile
      target: http-serve
    environment:
      DB_HOST: vspo-db
    depends_on:
      vspo-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - vspo-network
  datadog-agent:
    container_name: datadog-agent
    image: gcr.io/datadoghq/agent:latest
    environment:
      - DD_API_KEY=xxx
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_APM_RECEIVER_SOCKET=/var/run/datadog/apm.socket
      - DD_DOGSTATSD_SOCKET=/var/run/datadog/dsd.socket
      - DD_TRACE_AGENT_PORT=8126
      - DD_SITE=ap1.datadoghq.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/host/proc:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - vspo-network
networks:
  vspo-network:
    driver: bridge