version: "3.7"
services:
  vspo-db:
    container_name: vspo-db
    image: postgres:17
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vspo
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "psql -U user -d vspo -c 'SELECT 1'"]
      interval: 2s
      timeout: 1s
      retries: 5
    networks:
      - vspo-network
  neon-proxy:
    image: ghcr.io/timowilhelm/local-neon-http-proxy:main
    environment:
      - PG_CONNECTION_STRING=postgres://user:password@127.0.0.1:5432/vspo
    ports:
      - '4444:4444'
    depends_on:
      vspo-db:
        condition: service_healthy
    networks:
      - vspo-network
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.54
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - vspo-network
networks:
  vspo-network:
    driver: bridge
volumes:
  db_data:
