name = "vspo-portal-gateway"
compatibility_date = "2024-10-22"
send_metrics = false
compatibility_flags = ["nodejs_compat", "nodejs_als"]
main = "cmd/server/gateway.ts"
tail_consumers = [{ service = "api-tail" }]
logpush = true
kv_namespaces = [
  { binding = "APP_KV", id = "796f80b67f7b41b4b4e78474c34d8598" }
]

[dev]
port = 3000

[[services]]
binding = "APP_WORKER"
service = "vspo-portal-app"
entrypoint = "ApplicationService"

[vars]
SERVICE_NAME = "vspo-portal-gateway"
ENVIRONMENT = "production"
LOG_TYPE = "json"
LOG_MINLEVEL = "1"
LOG_HIDE_POSITION = "true"

[observability]
enabled = true
