name: 'Setup PNPM'
description: 'Setup Node.js and PNPM'
runs:
  using: 'composite'
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.10.0
        run_install: false

    - name: Download deps
      shell: bash
      run: pnpm install 

    - name: package build
      shell: bash
      run: pnpm build
