name: Deploy Agent

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'service/agent/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    strategy:
      matrix:
        include:
          - name: "vspo-portal-agent"
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.10.0
          run_install: false
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
        working-directory: service/agent
      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          packageManager: pnpm
          wranglerVersion: "4.6.0"
          workingDirectory: service/agent
          command: deploy --config .mastra/output/wrangler.json --name ${{ github.ref == 'refs/heads/main' && 'prd' || 'dev' }}-vspo-portal-agent
          quiet: true
          secrets: |
            CLOUDFLARE_ACCOUNT_ID
            CLOUDFLARE_PROJECT_NAME
            CLOUDFLARE_API_TOKEN
            OPENAI_ORGANIZATION
            OPENAI_PROJECT
            OPENAI_API_KEY
            OPENAI_BASE_URL
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_PROJECT_NAME: vspo-portal-agent
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          OPENAI_ORGANIZATION: ${{ secrets.OPENAI_ORGANIZATION }}
          OPENAI_PROJECT: ${{ secrets.OPENAI_PROJECT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
