name: Deploy Proxy Worker Preview
on:
  pull_request:
    branches: [main]
    paths:
      - 'service/vspo-schedule/**'
      - '.github/workflows/deploy-workers-preview.yaml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: service/vspo-schedule/proxy
    steps:
      - uses: actions/checkout@v4
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3.6.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: service/vspo-schedule/proxy
          environment: preview
          command: deploy --env preview
          secrets: |
            TRANSLATE_URL
            API_BASE_URL
        env:
          TRANSLATE_URL: ${{ secrets.TRANSLATE_URL }}
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
