name: PR Check
on:
  pull_request:
    paths:
      - 'service/server/**'
      - 'service/vspo-schedule/web/**'
      - '.github/workflows/pr-check.yaml'

jobs:
  biome-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PNPM
        uses: ./.github/actions/setup-pnpm
        
      - name: Biome Check
        run: pnpm biome:check

  typescript-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PNPM
        uses: ./.github/actions/setup-pnpm
        
      - name: TypeScript Check
        run: pnpm tsc

  server-check:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PNPM
        uses: ./.github/actions/setup-pnpm
        
      - name: Server Check
        run: pnpm run ci
        working-directory: service/server

  web-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PNPM
        uses: ./.github/actions/setup-pnpm
        
      - name: Lint
        run: |
          pnpm lint
        working-directory: service/vspo-schedule/web