name: PR Check
on:
  pull_request:
    paths:
      - 'service/server/**'
      - 'service/vspo-schedule/v2/web/**'
      - '.github/workflows/pr-check.yaml'

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      server: ${{ steps.filter.outputs.server }}
      web: ${{ steps.filter.outputs.web }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            server:
              - 'service/server/**'
            web:
              - 'service/vspo-schedule/v2/web/**'

  biome-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PNPM
        uses: ./.github/actions/setup-pnpm
        
      - name: Biome Check
        run: pnpm biome:check

  typescript-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PNPM
        uses: ./.github/actions/setup-pnpm
        
      - name: TypeScript Check
        run: pnpm tsc

  server-check:
    needs: changes
    if: ${{ needs.changes.outputs.server == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PNPM
        uses: ./.github/actions/setup-pnpm
        
      - name: Server Check
        run: pnpm run ci
        working-directory: service/server

  web-check:
    needs: changes
    if: ${{ needs.changes.outputs.web == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PNPM
        uses: ./.github/actions/setup-pnpm
        
      - name: Lint
        run: |
          pnpm lint
        working-directory: service/vspo-schedule/v2/web