name = "vspo-schedule-proxy"
compatibility_date = "2024-06-03"
send_metrics = false
compatibility_flags = ["nodejs_als"]
node_compat = true
main = "cmd/server/index.ts"
tail_consumers = [{ service = "vspo-schedule-proxy-tail" }]
logpush = true

[vars]
SERVICE_NAME = "vspo-schedule-proxy"
BASELIME_API_KEY = "xxx"
