name = "vspo-schedule-proxy"
compatibility_date = "2024-06-03"
send_metrics = false
main = "cmd/server/index.ts"
# tail_consumers = [{ service = "vspo-schedule-proxy-tail" }]
logpush = true

kv_namespaces = [
    { binding = "APP_KV", id = "5e5d47010ba44070ae8dbb819ed26a68" },
]

[vars]
SERVICE_NAME = "vspo-schedule-proxy"
BASELIME_API_KEY = "xxx"
TRANSLATE_URL = "xxx"
API_BASE_URL = "xxx"
