name = "vspo-schedule-proxy"
compatibility_date = "2024-06-03"
send_metrics = false
main = "cmd/server/index.ts"
# tail_consumers = [{ service = "vspo-schedule-proxy-tail" }]
logpush = true

[vars]
SERVICE_NAME = "vspo-schedule-proxy"
BASELIME_API_KEY = "xxx"

kv_namespaces = [
    { binding = "APP_KV", id = "4a001d176484425ba3e3c1226d80ee91" },
]
